// Builds lib/data/worldMap.ts: the world of the story as its author described
// it, our own world flipped north to south (Natural Earth coastlines, public
// domain, via the world-atlas package). Paradis is Madagascar; the Marleyan
// mainland is Africa. Madagascar comes from the 50m set, since the view
// starts on it; everything else is the 110m set, since it is only ever seen
// from far away.
//   run from a directory with world-atlas@2, topojson-client and d3-geo installed:
//   node <repo>/attack-on-titan-archive/scripts/world/map.mjs
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const req = createRequire(path.join(process.cwd(), "noop.js"));
const { feature } = req("topojson-client");
const { geoEquirectangular, geoPath, geoContains } = req("d3-geo");
const load = (n) => JSON.parse(fs.readFileSync(req.resolve(`world-atlas/${n}`), "utf8"));

const W = 1000;
const H = 760;
const proj = geoEquirectangular().reflectY(true).rotate([-25, 0]);
const box = { type: "Polygon", coordinates: [[[-22, -42], [-22, 48], [78, 48], [78, -42], [-22, -42]]] };
proj.fitExtent([[0, 0], [W, H]], { type: "Feature", geometry: box });
proj.clipExtent([[0, 0], [W, H]]);

// split a land MultiPolygon into Madagascar and the rest
const MAD = [46.9, -18.8];
function split(land) {
  const feats = land.type === "FeatureCollection" ? land.features : [land];
  const polys = feats.flatMap((f) => (f.geometry.type === "MultiPolygon" ? f.geometry.coordinates : [f.geometry.coordinates]));
  const isMad = (p) => geoContains({ type: "Polygon", coordinates: p }, MAD);
  return {
    mad: { type: "MultiPolygon", coordinates: polys.filter(isMad) },
    rest: { type: "MultiPolygon", coordinates: polys.filter((p) => !isMad(p)) },
  };
}
const fine = feature(load("land-50m.json"), load("land-50m.json").objects.land);
const coarse = feature(load("land-110m.json"), load("land-110m.json").objects.land);
const island = geoPath(proj).digits(2)(split(fine).mad);
const rest = geoPath(proj).digits(1)(split(coarse).rest);

const r = (v) => Math.round(v * 10) / 10;
const pt = (lon, lat) => proj([lon, lat]).map(r);
const out = `// Generated by scripts/world/map.mjs. Do not edit by hand.
// Natural Earth coastlines (public domain), flipped north to south.
export const MAP = {
  w: ${W},
  h: ${H},
  paradis: ${JSON.stringify(island)},
  land: ${JSON.stringify(rest)},
  /** the island's centre, and its two ends */
  paradisAt: ${JSON.stringify(pt(46.9, -18.8))},
  paradisEnds: ${JSON.stringify([pt(49.3, -12.0), pt(46.6, -25.6)])},
  /** a point well inside the Marleyan mainland, for its label */
  mainlandAt: ${JSON.stringify(pt(22, -14))},
  /** the open sea between them */
  seaAt: ${JSON.stringify(pt(38.5, -21))},
};
`;
const dest = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../lib/data/worldMap.ts");
fs.writeFileSync(dest, out);
console.log("wrote", dest, Math.round(out.length / 1024), "KB");
